### ISSUE TITLE
Multiple Reusable Api Hosts

### ISSUE THREAD

**Issue by stephenweinrich** [SlalomBuild/blackslope.net#22] opened 2019-10-07 13:18 UTC
Can we create a NuGet package for the reusable api host code? If I wanted to create multiple api hosts I would be duplicating a lot of the common code. Perhaps an official Slalom.BlackSlope.Api.Core could solve this. If the Api layer was really thin maybe only specifying operations, models, mappers and validated and then all the other common code could go into NuGet package. Common could should be open source too so that it can be contributed to, a new repo will be required. Perhaps we could get. GitHub Project called BlackSlope and then have multiple repos to support Api and NuGet package code.

**Comment by pmotameni** [comment] 2019-10-07 14:41
This is a great idea, I started this but hit a blocker, because either we do need a place to host the NuGet or we have to implement a way to build API with Api.Core.  I would like to have the former.

**Comment by theczorn** [comment] 2021-08-02 15:12
Technically a Duplicate Of #35

**Closed** 2021-08-02 15:12 UTC
Labels: enhancement
